import type { Theme } from "./tokens.js";

/**
 * The theme catalog: 18 distinct looks for the news composition.
 *
 * These are not palette swaps. Each theme picks a different combination of
 * *structural* variants — where the ticker sits and whether it's a solid band,
 * discrete chips, a thin ribbon or absent entirely; whether the headline plate is
 * a bar, a floating card, a rule-underline or a corner tag; which side it enters
 * from; how segments give way to each other — so two themes differ in composition
 * and rhythm, not only colour.
 *
 * Transition frame counts vary per theme (12–24). render-server keys its
 * targeted-re-render invalidation off this number, so it is load-bearing, not
 * decorative.
 */

const SANS = "'Segoe UI', Inter, Roboto, Helvetica, Arial, sans-serif";
const SANS_WIDE = "Verdana, Geneva, 'DejaVu Sans', sans-serif";
const CONDENSED = "'Franklin Gothic Medium', 'Arial Narrow', 'Liberation Sans Narrow', sans-serif";
const IMPACT = "Impact, Haettenschweiler, 'Arial Black', sans-serif";
const SERIF = "Georgia, 'Times New Roman', 'Liberation Serif', serif";
const SERIF_DISPLAY = "'Palatino Linotype', Palatino, 'URW Palladio L', serif";
const MONO = "'Courier New', 'DejaVu Sans Mono', monospace";
const HUMANIST = "'Trebuchet MS', 'Lucida Grande', 'DejaVu Sans', sans-serif";

export const THEMES: readonly Theme[] = [
  {
    id: "midnight-wire",
    name: "Midnight Wire",
    description: "Deep navy newsroom with a hard red accent — the classic late-bulletin look.",
    palette: {
      base: "#070b14",
      surface: "#0d1424ee",
      accent: "#e11d2e",
      accentSoft: "#ff5a68",
      textPrimary: "#ffffff",
      textMuted: "#9fb0c9",
      captionActive: "#ff5a68",
      scrimStrength: 0.65,
    },
    fonts: {
      headline: SANS,
      headlineWeight: 800,
      headlineTransform: "none",
      headlineTracking: 0,
      caption: SANS,
      captionWeight: 800,
    },
    ticker: { variant: "band", badge: "BREAKING", speed: 160, heightScale: 1 },
    lowerThird: { variant: "accentBar", align: "left", enter: "slideX" },
    captions: { variant: "highlightWord", weight: 800, sizeScale: 1 },
    intro: "barsWipe",
    outro: "cardsUp",
    transition: { style: "crossfade", frames: 15 },
  },
  {
    id: "broadsheet",
    name: "Broadsheet",
    description: "Cream paper stock and serif headlines — print journalism translated to motion.",
    palette: {
      base: "#f4f1e8",
      surface: "#f9f7f1f2",
      accent: "#1a1a1a",
      accentSoft: "#8c1c13",
      textPrimary: "#14140f",
      textMuted: "#5b5a51",
      captionActive: "#8c1c13",
      scrimStrength: 0.35,
    },
    fonts: {
      headline: SERIF,
      headlineWeight: 700,
      headlineTransform: "none",
      headlineTracking: 0,
      caption: SERIF,
      captionWeight: 700,
    },
    ticker: { variant: "minimal", badge: null, speed: 110, heightScale: 0.7 },
    lowerThird: { variant: "underline", align: "left", enter: "fadeUp" },
    captions: { variant: "underlineWord", weight: 700, sizeScale: 0.95 },
    intro: "minimalRule",
    outro: "ruleCollapse",
    transition: { style: "wipeX", frames: 18 },
  },
  {
    id: "signal-red",
    name: "Signal Red",
    description: "Black field, oversized condensed type, headline chips — urgent and graphic.",
    palette: {
      base: "#000000",
      surface: "#101010f0",
      accent: "#ff2d2d",
      accentSoft: "#ff8a8a",
      textPrimary: "#ffffff",
      textMuted: "#a8a8a8",
      captionActive: "#ff2d2d",
      scrimStrength: 0.7,
    },
    fonts: {
      headline: IMPACT,
      headlineWeight: 400,
      headlineTransform: "uppercase",
      headlineTracking: 2,
      caption: CONDENSED,
      captionWeight: 700,
    },
    ticker: { variant: "chips", badge: "LIVE", speed: 190, heightScale: 1.1 },
    lowerThird: { variant: "blockShadow", align: "left", enter: "slideX" },
    captions: { variant: "chipWord", weight: 700, sizeScale: 1.05 },
    intro: "centerPulse",
    outro: "sideSlide",
    transition: { style: "slideX", frames: 12 },
  },
  {
    id: "arctic",
    name: "Arctic",
    description: "Bright, airy ice-blue with a floating card plate — calm explanatory register.",
    palette: {
      base: "#eef4f8",
      surface: "#ffffffe8",
      accent: "#0a7ea4",
      accentSoft: "#5fc4e0",
      textPrimary: "#0b1b25",
      textMuted: "#4a6675",
      captionActive: "#0a7ea4",
      scrimStrength: 0.3,
    },
    fonts: {
      headline: HUMANIST,
      headlineWeight: 700,
      headlineTransform: "none",
      headlineTracking: 0,
      caption: HUMANIST,
      captionWeight: 700,
    },
    ticker: { variant: "ribbon", badge: null, speed: 130, heightScale: 0.8 },
    lowerThird: { variant: "card", align: "left", enter: "scaleIn" },
    captions: { variant: "boxedLine", weight: 700, sizeScale: 0.95 },
    intro: "gridReveal",
    outro: "centerFade",
    transition: { style: "zoomIn", frames: 20 },
  },
  {
    id: "dispatch",
    name: "Dispatch",
    description: "Warm charcoal and amber, stacked rules — field-report warmth.",
    palette: {
      base: "#141110",
      surface: "#1e1a17ee",
      accent: "#f0a202",
      accentSoft: "#ffd166",
      textPrimary: "#fdf6ec",
      textMuted: "#b8a894",
      captionActive: "#f0a202",
      scrimStrength: 0.6,
    },
    fonts: {
      headline: CONDENSED,
      headlineWeight: 700,
      headlineTransform: "uppercase",
      headlineTracking: 1,
      caption: SANS,
      captionWeight: 700,
    },
    // Chips rather than a band: "band" was carrying six themes and made dispatch
    // read as a sibling of frontline and midnight-wire.
    ticker: { variant: "chips", badge: "DISPATCH", speed: 145, heightScale: 1 },
    lowerThird: { variant: "stackedRule", align: "left", enter: "fadeUp" },
    captions: { variant: "highlightWord", weight: 700, sizeScale: 1 },
    intro: "cornerSlate",
    outro: "cardsUp",
    transition: { style: "crossfade", frames: 16 },
  },
  {
    id: "neon-brief",
    name: "Neon Brief",
    description: "Near-black with cyan/magenta chips and a colour-dip cut — tech-desk energy.",
    palette: {
      base: "#05060a",
      surface: "#0b0f1ae8",
      accent: "#00e5ff",
      accentSoft: "#ff3ec8",
      textPrimary: "#eafcff",
      textMuted: "#7f95a8",
      captionActive: "#ff3ec8",
      scrimStrength: 0.68,
    },
    fonts: {
      headline: SANS,
      headlineWeight: 800,
      headlineTransform: "uppercase",
      headlineTracking: 3,
      caption: MONO,
      captionWeight: 700,
    },
    ticker: { variant: "chips", badge: "FEED", speed: 200, heightScale: 1 },
    lowerThird: { variant: "cornerTag", align: "right", enter: "wipeX" },
    captions: { variant: "chipWord", weight: 700, sizeScale: 0.9 },
    intro: "gridReveal",
    outro: "sideSlide",
    transition: { style: "dipToColor", frames: 14 },
  },
  {
    id: "sterling",
    name: "Sterling",
    description: "Deep forest green and brushed gold, serif display — markets and institutions.",
    palette: {
      base: "#0a1410",
      surface: "#102019ee",
      accent: "#c9a227",
      accentSoft: "#e8cf7a",
      textPrimary: "#f5f2e7",
      textMuted: "#9fb3a5",
      captionActive: "#e8cf7a",
      scrimStrength: 0.62,
    },
    fonts: {
      headline: SERIF_DISPLAY,
      headlineWeight: 700,
      headlineTransform: "none",
      headlineTracking: 0,
      caption: SANS,
      captionWeight: 700,
    },
    ticker: { variant: "minimal", badge: null, speed: 120, heightScale: 0.75 },
    lowerThird: { variant: "card", align: "left", enter: "fadeUp" },
    captions: { variant: "highlightWord", weight: 700, sizeScale: 0.95 },
    intro: "minimalRule",
    outro: "centerFade",
    transition: { style: "crossfade", frames: 22 },
  },
  {
    id: "bulletin-mono",
    name: "Bulletin Mono",
    description: "Greyscale monospace teletype — wire-service austerity, no colour at all.",
    palette: {
      base: "#0e0e0e",
      surface: "#1a1a1af2",
      accent: "#e8e8e8",
      accentSoft: "#9a9a9a",
      textPrimary: "#f5f5f5",
      textMuted: "#8f8f8f",
      captionActive: "#ffffff",
      scrimStrength: 0.66,
    },
    fonts: {
      headline: MONO,
      headlineWeight: 700,
      headlineTransform: "uppercase",
      headlineTracking: 2,
      caption: MONO,
      captionWeight: 700,
    },
    ticker: { variant: "band", badge: "WIRE", speed: 150, heightScale: 0.9 },
    lowerThird: { variant: "underline", align: "left", enter: "wipeX" },
    captions: { variant: "underlineWord", weight: 700, sizeScale: 0.9 },
    intro: "cornerSlate",
    outro: "ruleCollapse",
    transition: { style: "wipeX", frames: 12 },
  },
  {
    id: "crimson-desk",
    name: "Crimson Desk",
    description: "Slate grey with crimson ribbon and a right-aligned plate — anchor-desk formality.",
    palette: {
      base: "#15171c",
      surface: "#1d2027ee",
      accent: "#c1121f",
      accentSoft: "#ef6461",
      textPrimary: "#f7f7f8",
      textMuted: "#9ba3af",
      captionActive: "#ef6461",
      scrimStrength: 0.63,
    },
    fonts: {
      headline: SANS_WIDE,
      headlineWeight: 700,
      headlineTransform: "none",
      headlineTracking: 0,
      caption: SANS,
      captionWeight: 800,
    },
    ticker: { variant: "ribbon", badge: "NEWS", speed: 155, heightScale: 0.85 },
    lowerThird: { variant: "accentBar", align: "right", enter: "slideX" },
    captions: { variant: "highlightWord", weight: 800, sizeScale: 1 },
    intro: "barsWipe",
    outro: "sideSlide",
    transition: { style: "slideX", frames: 15 },
  },
  {
    id: "oceanic",
    name: "Oceanic",
    description: "Deep teal with a soft card plate and a slow zoom — long-form documentary pacing.",
    palette: {
      base: "#04161c",
      surface: "#0a2630e6",
      accent: "#2ec4b6",
      accentSoft: "#8ae9df",
      textPrimary: "#eefcfa",
      textMuted: "#84a8ad",
      captionActive: "#2ec4b6",
      scrimStrength: 0.6,
    },
    fonts: {
      headline: HUMANIST,
      headlineWeight: 700,
      headlineTransform: "none",
      headlineTracking: 0,
      caption: HUMANIST,
      captionWeight: 700,
    },
    ticker: { variant: "band", badge: null, speed: 125, heightScale: 0.95 },
    lowerThird: { variant: "card", align: "left", enter: "scaleIn" },
    captions: { variant: "boxedLine", weight: 700, sizeScale: 0.95 },
    intro: "centerPulse",
    outro: "centerFade",
    transition: { style: "zoomIn", frames: 24 },
  },
  {
    id: "paper-trail",
    name: "Paper Trail",
    description: "Off-white light theme with ink-black rules — investigative, document-forward.",
    palette: {
      base: "#fbfaf7",
      surface: "#ffffffee",
      accent: "#1b1b1b",
      accentSoft: "#6b6b6b",
      textPrimary: "#111111",
      textMuted: "#5f5f5f",
      captionActive: "#1b1b1b",
      scrimStrength: 0.32,
    },
    fonts: {
      headline: SANS,
      headlineWeight: 800,
      headlineTransform: "uppercase",
      headlineTracking: 1,
      caption: SANS,
      captionWeight: 700,
    },
    ticker: { variant: "minimal", badge: null, speed: 115, heightScale: 0.7 },
    lowerThird: { variant: "stackedRule", align: "left", enter: "fadeUp" },
    captions: { variant: "boxedLine", weight: 700, sizeScale: 0.9 },
    intro: "minimalRule",
    outro: "ruleCollapse",
    transition: { style: "crossfade", frames: 18 },
  },
  {
    id: "vantage",
    name: "Vantage",
    description: "Slate and violet with block-shadow type — analysis and commentary.",
    palette: {
      base: "#12111c",
      surface: "#1b1930ee",
      accent: "#7c5cff",
      accentSoft: "#b9a6ff",
      textPrimary: "#f3f1ff",
      textMuted: "#9a94bb",
      captionActive: "#b9a6ff",
      scrimStrength: 0.64,
    },
    fonts: {
      headline: SANS,
      headlineWeight: 800,
      headlineTransform: "none",
      headlineTracking: 0,
      caption: SANS,
      captionWeight: 800,
    },
    ticker: { variant: "chips", badge: null, speed: 170, heightScale: 1 },
    lowerThird: { variant: "blockShadow", align: "left", enter: "slideX" },
    captions: { variant: "highlightWord", weight: 800, sizeScale: 1 },
    intro: "gridReveal",
    outro: "cardsUp",
    transition: { style: "slideX", frames: 14 },
  },
  {
    id: "ember",
    name: "Ember",
    description: "Black with molten orange and a colour-dip cut — conflict and breaking crisis.",
    palette: {
      base: "#0a0705",
      surface: "#160f0aee",
      accent: "#ff6b1a",
      accentSoft: "#ffb066",
      textPrimary: "#fff6ef",
      textMuted: "#b3968a",
      captionActive: "#ff6b1a",
      scrimStrength: 0.7,
    },
    fonts: {
      headline: IMPACT,
      headlineWeight: 400,
      headlineTransform: "uppercase",
      headlineTracking: 2,
      caption: CONDENSED,
      captionWeight: 700,
    },
    ticker: { variant: "band", badge: "URGENT", speed: 185, heightScale: 1.1 },
    lowerThird: { variant: "cornerTag", align: "left", enter: "wipeX" },
    captions: { variant: "chipWord", weight: 700, sizeScale: 1.05 },
    intro: "centerPulse",
    outro: "sideSlide",
    transition: { style: "dipToColor", frames: 13 },
  },
  {
    id: "civic",
    name: "Civic",
    description: "Institutional navy and white with a clean ribbon — politics and policy.",
    palette: {
      base: "#0b1f3a",
      surface: "#102a4cee",
      accent: "#ffffff",
      accentSoft: "#8fb8e8",
      textPrimary: "#ffffff",
      textMuted: "#a9c2de",
      captionActive: "#ffd24a",
      scrimStrength: 0.6,
    },
    fonts: {
      headline: SANS_WIDE,
      headlineWeight: 700,
      headlineTransform: "uppercase",
      headlineTracking: 1,
      caption: SANS,
      captionWeight: 700,
    },
    ticker: { variant: "ribbon", badge: "REPORT", speed: 135, heightScale: 0.85 },
    lowerThird: { variant: "stackedRule", align: "left", enter: "fadeUp" },
    captions: { variant: "highlightWord", weight: 700, sizeScale: 0.95 },
    intro: "barsWipe",
    outro: "centerFade",
    transition: { style: "wipeX", frames: 17 },
  },
  {
    id: "noir",
    name: "Noir",
    description: "Pure black and white, no ticker at all — maximum-contrast minimalism.",
    palette: {
      base: "#000000",
      surface: "#ffffffea",
      accent: "#ffffff",
      accentSoft: "#c9c9c9",
      textPrimary: "#ffffff",
      textMuted: "#9c9c9c",
      captionActive: "#ffffff",
      scrimStrength: 0.72,
    },
    fonts: {
      headline: SERIF_DISPLAY,
      headlineWeight: 700,
      headlineTransform: "uppercase",
      headlineTracking: 4,
      caption: SERIF,
      captionWeight: 700,
    },
    ticker: { variant: "none", badge: null, speed: 0, heightScale: 0 },
    lowerThird: { variant: "underline", align: "left", enter: "fadeUp" },
    captions: { variant: "underlineWord", weight: 700, sizeScale: 1.05 },
    intro: "minimalRule",
    outro: "ruleCollapse",
    transition: { style: "crossfade", frames: 24 },
  },
  {
    id: "meridian",
    name: "Meridian",
    description: "Indigo with acid-lime accents and a zoom cut — science and data stories.",
    palette: {
      base: "#0d1030",
      surface: "#161a44e8",
      accent: "#c6ff4a",
      accentSoft: "#e4ff9e",
      textPrimary: "#f2f4ff",
      textMuted: "#9297c4",
      captionActive: "#c6ff4a",
      scrimStrength: 0.65,
    },
    fonts: {
      headline: SANS,
      headlineWeight: 800,
      headlineTransform: "uppercase",
      headlineTracking: 2,
      caption: MONO,
      captionWeight: 700,
    },
    ticker: { variant: "chips", badge: "DATA", speed: 175, heightScale: 1 },
    lowerThird: { variant: "card", align: "right", enter: "scaleIn" },
    captions: { variant: "chipWord", weight: 700, sizeScale: 0.9 },
    intro: "gridReveal",
    outro: "cardsUp",
    transition: { style: "zoomIn", frames: 19 },
  },
  {
    id: "frontline",
    name: "Frontline",
    description: "Olive drab with field green — on-the-ground correspondent reporting.",
    palette: {
      // Moved out of the yellow family (was #b5c400 lime, which read as a third
      // variation on dispatch's amber and sterling's gold). Field green is
      // thematically right here and was an unused hue in the catalog.
      base: "#12140d",
      surface: "#1c1f14ee",
      accent: "#6d9b3f",
      accentSoft: "#a9cd7a",
      textPrimary: "#f7f8ee",
      textMuted: "#a8ad8f",
      captionActive: "#a9cd7a",
      scrimStrength: 0.66,
    },
    fonts: {
      headline: CONDENSED,
      headlineWeight: 700,
      headlineTransform: "uppercase",
      headlineTracking: 1,
      caption: SANS,
      captionWeight: 800,
    },
    ticker: { variant: "band", badge: "FIELD", speed: 165, heightScale: 1.05 },
    lowerThird: { variant: "accentBar", align: "left", enter: "slideX" },
    captions: { variant: "highlightWord", weight: 800, sizeScale: 1 },
    intro: "cornerSlate",
    outro: "sideSlide",
    transition: { style: "slideX", frames: 13 },
  },
  {
    id: "pulse",
    name: "Pulse",
    description: "Magenta on deep plum with block-shadow plates — culture and media desk.",
    palette: {
      base: "#160a18",
      surface: "#231029ee",
      accent: "#ff2d95",
      accentSoft: "#ff93c8",
      textPrimary: "#fff0f8",
      textMuted: "#b98fac",
      captionActive: "#ff93c8",
      scrimStrength: 0.64,
    },
    fonts: {
      headline: SANS,
      headlineWeight: 800,
      headlineTransform: "none",
      headlineTracking: 0,
      caption: HUMANIST,
      captionWeight: 800,
    },
    ticker: { variant: "ribbon", badge: null, speed: 180, heightScale: 0.9 },
    lowerThird: { variant: "blockShadow", align: "right", enter: "wipeX" },
    captions: { variant: "boxedLine", weight: 800, sizeScale: 1 },
    intro: "centerPulse",
    outro: "cardsUp",
    transition: { style: "dipToColor", frames: 16 },
  },
];

export const DEFAULT_THEME_ID = "midnight-wire";

const THEME_BY_ID = new Map(THEMES.map((theme) => [theme.id, theme]));

export function getTheme(themeId: string): Theme {
  const theme = THEME_BY_ID.get(themeId);
  if (!theme) {
    throw new Error(`Unknown theme id "${themeId}". Known ids: ${THEMES.map((t) => t.id).join(", ")}`);
  }
  return theme;
}

/** Non-throwing lookup for callers that want to fall back rather than fail a render. */
export function getThemeOrDefault(themeId: string | null | undefined): Theme {
  if (!themeId) return getTheme(DEFAULT_THEME_ID);
  return THEME_BY_ID.get(themeId) ?? getTheme(DEFAULT_THEME_ID);
}

export const THEME_IDS: readonly string[] = THEMES.map((theme) => theme.id);
